apiVersion: v1
kind: Namespace
metadata:
  name: pmipam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmipam
  namespace: pmipam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmipam
  template:
    metadata:
      labels:
        app: pmipam
    spec:
      containers:
      - name: pmipam
        image: ofthetimelords/vtable.pmipam:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: Hosts
          value: "/data/hosts.yml"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          configMap:
            name: hosts
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: pmipam
  namespace: pmipam
spec:
  type: ClusterIP
  selector:
    app: pmipam
  ports:
  - name: web
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: pmipam
  namespace: pmipam
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pmipam
              port:
                name: "web"
  tls:
  - secretName: secret
    hosts:
      - hostname
